### ISSUE TITLE
Couldn't launch BML in my Ballance.

### ISSUE THREAD

**Issue by yyc12345** [Gamepiaynmo/BallanceModLoader#1]
BML crash when I install it on my Ballance.

Ballance version: original 1.13 english
Windows version: Windows 10 1903
Used BML version: a830065
VC compiler version: 19.23.28106.4

BML crashed. But I got 4 folders in ModLoader folder: `Cache`, `Config`, `Maps` and `Mods`. But all of them are empty.
And, I got `ModLoader.log`, but it still is empty.

I use Visual Studio 2019 to debug this dll. And it report:
`0x240360AD (CK2.dll)处(位于 Player.exe 中)引发的异常: 0xC0000005: 读取位置 0x00000004 时发生访问冲突。`
It seems like CK2.dll's problem. I couldn't locate any code which comes from BML. and debugger stuck in this exception.

**Comment by Gamepiaynmo** [comment]
The code is not finished and not ready to be released now. Please wait for the first release.
