### ISSUE TITLE
How can I compile and build this project for myself?

### ISSUE THREAD

**Issue by Swung0x48** [Gamepiaynmo/BallanceModLoader#2]
Which runtime, SDK or dependencies do I need so that I can compile and build this for myself?
Just found this work is brilliant and I personally wanna contribute a bit to it.
FYI, I tried to compile it and it's spitting out `unexpected end of file while looking for precompiled header. Did you forget to add #include "pch.h" to your source?` all over the place. It seems to be a precompiled header? No idea what to do with that.
 I have no idea if anything else is required, so I turned here for help.

**Comment by Gamepiaynmo** [comment]
A "Building" section has been added to Readme. Please follow these steps:

Building

* Clone this repository.
* Open BML.sln with Visual Studio 2019.
* Go to Project Properties -> C/C++ -> Precompile Header, and disable it.
* Set building configuration to Release, x86.
* Change the output path to what you want.
* Build the solution.
