### ISSUE TITLE
Mod with reference to 3rd party dlls could not load properly

### ISSUE THREAD

**Issue by Swung0x48** [Gamepiaynmo/BallanceModLoader#4]
I'm using a C++ library cpr in my mod, and it has libcurl as its dependency.
My mod loads just fine when I comment out the usage of external libraries. But it does not show up in the mod list once I started using these libraries.
The code I've written may help you diagnose the problem. Hopefully.
https://github.com/Swung0x48/BallanceRecord/blob/master/BallanceRecordClient/BallanceRecordClient.cpp

**Comment by Gamepiaynmo** [comment]
Fixed in version 0.3.28.

**Comment by Swung0x48** [comment]
It works!
