### ISSUE TITLE
Game abruptly ends after I load Chinese worded maps to Modloader folder

### ISSUE THREAD

**Issue by hexapling** [Gamepiaynmo/BallanceModLoader#5]
When I copy and paste a few Chinese based file name maps into the ModLoader\Maps folder, the game starts, followed by a black screen, then quits by itself. 
See the folder here:

 ![Chinese and English Maps](https://user-images.githubusercontent.com/43799601/95673776-92a44980-0bf7-11eb-9022-fdf618d2cc71.jpg)

However, when I delete the Chinese worded files and leave only the English, the game and BML loads and works as normal: 

![English Maps](https://user-images.githubusercontent.com/43799601/95673793-aa7bcd80-0bf7-11eb-9b65-3aadd32b3a6a.jpg)
![Normal Load](https://user-images.githubusercontent.com/43799601/95673883-3261d780-0bf8-11eb-9fce-c2b955a27124.jpg)

Here is the log: 
[ModLoader.log](https://github.com/Gamepiaynmo/BallanceModLoader/files/5360775/ModLoader.log)

I'm running Windows 10 Home (English (US)). Sorry I don't know anything about programming or modding, just a simple user and fan of the game. TIA

**Comment by Gamepiaynmo** [comment]
Thanks for pointing it out. A workaround is now applied to convert Chinese file names into Pinyin, not sure if it works well in pure English OS environment. Please give the latest version a try.
